apiVersion: v1
kind: Deployment
metadata:
  name: helpmeai
  labels:
    app: helpmeai
spec:
  selector:
    matchLabels:
      app: helpmeai
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helpmeai
    spec:
      containers:
      - name: helpmeai
        image: depoamine/helpmeai-showcase:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        ports:
        - containerPort: 80
      restartPolicy: Always